### ISSUE TITLE
Update the project card background based on the status

### ISSUE THREAD

**Issue by haroon-sheikh** [sitture/commit-status#68]
# Task

- [x] Update the project card background based on the status. E.g. if the status is success then change the background of the project card to green. 
- [x] Remove the status column
- [x] Right align the action to remove project

**Comment by sk6298** [comment]
I want to give it a try

**Comment by sachinttn9663** [comment]
@haroon-sheikh, ok, assign it to me, will work on it

**Comment by Sachin9663** [comment]
@haroon-sheikh , PR created for all three points, Please review
